### ISSUE TITLE
SPSE versi 4.4

### ISSUE THREAD

**Issue by nplify09** [wakataw/pyproc#24]
terjadi error ketika download data dari SPSE dengan versi 4.4. cth : lpse.maroskab.go.id
blank di kolom npwp, nama_peserta, penawaran, penawaran_terkoreksi, dan hasil_negosiasi
![pyproc](https://user-images.githubusercontent.com/76137303/126613986-9255a4a1-31ea-4b44-bee8-c3670f4bb113.JPG)

**Comment by nplify09** [comment]
maaf mas, ini caranya gmna ya? saya coba tapi hasilnya masih sama. mohon petunjuknya

**Comment by wakataw** [comment]
Di upgrade dulu mas

**Comment by nplify09** [comment]
cara upgradenya gmna mas?

**Comment by nplify09** [comment]
> 
> 
> cara upgradenya gmna mas?

aman mas, terimakasih
