### ISSUE TITLE
PyProc 1.8

### ISSUE THREAD

**Issue by oraclecentrino** [wakataw/pyproc#27]
Ketika menggabungkan data di lpse.pu.go.id terdapat pesan error **"ERROR: Expecting value: line 1 column 1 (char 0)"**

![Capture_lpse_pu](https://user-images.githubusercontent.com/15371904/130535035-848aca8a-ae1d-47df-8edf-ae5de959404f.JPG)

Querynya seperti ini : **pyproc --host lpse.pu.go.id;hasil-pu.csv --workers 30 --timeout 600 --fetch-size 1000**

Terima Kasih

**Comment by wakataw** [comment]
Ini kemungkinan ada salah satu dari file detail yang didownload tapi hasilnya kosong. Bisa diupload folder downloadnya mas? Bisa di zip dulu supaya ukurannya kecil.

Terima kasih.

**Comment by oraclecentrino** [comment]
Saya ulangi lagi jadinya mas.. dan error nya hilang

**Comment by oraclecentrino** [comment]
khusus untuk website LPSE dengan pesan error "menggabungkan 'NoneType' object is not subscriptable" ini data tarikan nya yang gagal gabung

[LPSE_Error.zip](https://github.com/wakataw/pyproc/files/7043493/LPSE_Error.zip)

Terima Kasih
