### ISSUE TITLE
Error PyProc 1.8 Gagal Identifikasi Aplikasi SPSE

### ISSUE THREAD

**Issue by oraclecentrino** [wakataw/pyproc#28]
ada beberapa web lpse yang oleh pyproc, disebut bukan web lpse ,padahal web tersebut adaas, seperti contoh dibawah ini 

![error_lpse_new](https://user-images.githubusercontent.com/15371904/130630574-1ec8d186-7592-4d21-83dc-abec7fbb3746.JPG)

Terima kasih

**Comment by oraclecentrino** [comment]
Permisi mas, ini ada beberapa website LPSE yang gagal download data dan pesan errornya

[Book3.xlsx](https://github.com/wakataw/pyproc/files/7042587/Book3.xlsx)

dan khusus untuk website LPSE dengan pesan error **"menggabungkan 'NoneType' object is not subscriptable"** ini data tarikan nya yang gagal gabung

[LPSE_Error.zip](https://github.com/wakataw/pyproc/files/7042593/LPSE_Error.zip)

Terima Kasih

**Comment by wakataw** [comment]
Terkait masalah gagal menggabungkan data nanti dijawab di #27 sini ya mas.

Kalo terkait gagal identifikasi aplikasi spse ini kemungkinan karena di daftar host nya gak dikasih protokol (http/https). Kalo gak dikasih protokol, kita defaultnya ke http dulu, ini tergantung dari sisi server apa di redirect ke https atau nggak. Kalo nggak diarahkan ke https, biasanya gak masuk ke aplikasi SPSEnya.

Solusinya bisa dikasih langsung protokol di daftar host nya https://lpse.blabla.go.id, sesuaikan di website asli apakah http atau https.

Atau bisa juga pake parameter `--skip-spse-check`, ini biar pyprocnya langsung aja jalan tanpa cek ini aplikasi spse atau bukan.

**Comment by oraclecentrino** [comment]
Sudah saya upload ulang di https://github.com/wakataw/pyproc/issues/27 ini mas..mohon bantuannya

**Comment by wakataw** [comment]
maaf mas, ini sudah fix kan ya?
atau masih ada problem?

sementara saya close dulu
