### ISSUE TITLE
Error Scrape

### ISSUE THREAD

**Issue by heceheme** [wakataw/pyproc#31]
nyoba scrape dari lpse.lampungprov.go.id ga bisa. tanpa tampilan error. 
![Capture](https://user-images.githubusercontent.com/17428265/131947054-7dc6e2f5-62d8-4ca1-96f4-18b0b056af47.PNG)

**Comment by wakataw** [comment]
Ini sudah fix di versi 0.1.9 mas, cuma memang belum direlease karena belum selesai dikerjakan.
Kalau mau coba atau butuh cepat bisa langsung install
```
pip install -i https://test.pypi.org/simple/ pyproc==0.1.9a2021090302
```

**Comment by heceheme** [comment]
terimakasih respon nya. saya sudah coba versi 1.9 tp malah muncul error
![Capture](https://user-images.githubusercontent.com/17428265/132170037-b911d34d-ee98-4f47-9a31-a957a9b52bed.PNG)
terima kasih

**Comment by wakataw** [comment]
ini argumen yang dipakai apa aja mas?

**Comment by heceheme** [comment]
-pyproc lpse.jakarta.go.id
-pyproc
lpse.metrokota.go.id

**Comment by wakataw** [comment]
solusi sementara bisa upgrade ke python 3.7 atau versi atasnya mas

**Comment by oraclecentrino** [comment]
permisi mas python saya sudah versi 3.9.6

dan install pyproc nya menggunakan syntak : **pip install -i https://test.pypi.org/simple/ pyproc==0.1.9a2021090602 --upgrade**

dan berhasil

![pyrpoc1](https://user-images.githubusercontent.com/15371904/132205461-b9ea4b90-eb54-4099-b4ea-c12c7f68e59f.png)

namun ketika saya coba narik data, muncul error sperti dibawah ini:

![pyproc2](https://user-images.githubusercontent.com/15371904/132205545-d4182dbb-2415-4dd6-b1bf-7ab5100e48e9.png)

Terima Kasih

**Comment by wakataw** [comment]
Maaf mas, ini saya gak bisa reproduce errornya sama sekali. Saya coba install dan download sesuai spse yang dicoba di windows, gak ada yang error.
Mungkin bisa dicoba install ulang lagi aplikasi pyprocnya, terus pake `--force-reinstall` biar maksa install ulang semua dan pastikan gak ada yang error. 

Atau ini kalo mau coba versi yang dicompile, masih coba-coba, khusus untuk windows 64 bit.

[pyproc-v0.1.9a2021090601-win64.zip](https://github.com/wakataw/pyproc/files/7117077/pyproc-v0.1.9a2021090601-win64.zip)

**Comment by oraclecentrino** [comment]
ijin mas..bisa minta file *.tar.gz nya..soalnya saya coba masih error

terima kasih

**Comment by oraclecentrino** [comment]
masih error ini mas

![pyproc_err1](https://user-images.githubusercontent.com/15371904/132266231-470e843f-6777-4426-95e7-07faae0d6cee.JPG)

saya instalnya pake argumen ini :

pip install git+https://github.com/wakataw/pyproc.git

**Comment by wakataw** [comment]
> masih error ini mas
> 
> ![pyproc_err1](https://user-images.githubusercontent.com/15371904/132266231-470e843f-6777-4426-95e7-07faae0d6cee.JPG)
> 
> saya instalnya pake argumen ini :
> 
> pip install git+https://github.com/wakataw/pyproc.git
> 
> Terima Kasih

tambaha --force-reinstall di belakang mas
`pip install git+https://github.com/wakataw/pyproc.git --force-reinstall`

**Comment by oraclecentrino** [comment]
Mantap, berhasil mas

btw untuk yg versi 0.1.9 nya tidak bisa lagi load alamat lpse dari csv ya mas

Terima Kasih

**Comment by wakataw** [comment]
> Mantap, berhasil mas
> 
> btw untuk yg versi 0.1.9 nya tidak bisa lagi load alamat lpse dari csv ya mas
> 
> Terima Kasih

tetap bisa mas, di versi 0.1.9 alamat lpsenya tinggal diganti nama file

`pyproc daftar-lpse.txt`

**Comment by oraclecentrino** [comment]
siap terima kasih mas

btw versi stable nya 0.1.9 kapan di realese nih mas :D

**Comment by oraclecentrino** [comment]
waktu download detail terjadi error seperti dibawah ini mas

![pyproc_err3](https://user-images.githubusercontent.com/15371904/132336888-de1593d4-8a4e-4700-ade7-a9afefe63072.JPG)

Terima Kasih

**Comment by wakataw** [comment]
> waktu download detail terjadi error seperti dibawah ini mas
> 
> ![pyproc_err3](https://user-images.githubusercontent.com/15371904/132336888-de1593d4-8a4e-4700-ade7-a9afefe63072.JPG)
> 
> Terima Kasih

Error di sisi aplikasi spsenya ini gak bisa di prediksi mas, kadang error kadang nggak untuk halaman detilnya.
Itu coba dibuka halaman detail yang di keterangan errornya, kalo seandainya bisa dibuka, mungkin bisa di resume aja prosesnya.

`pyproc lpse.jakarta.go.id --keep-index` ini supaya file indexnya (xxx.idx) gak didelete kalo proses selesai.

nah, nanti setelah proses selesai ketahuan kan berapa yang error, kalau mau diulang tinggal tambah parameter `--resume`

`pyproc lpse.jakarta.go.id --keep-index --resume` 

nanti aplikasinya cuma download yang error aja

**Comment by wakataw** [comment]
Issue saya close dulu, karena sudah oot dari issue awal.
