### ISSUE TITLE
Salah parsing nama paket non tender

### ISSUE THREAD

**Issue by wakataw** [wakataw/pyproc#42]
Pada kolom nama paket di database index salah mapping, sehingga data yang masuk nilai kontrak.

**Comment by oraclecentrino** [comment]
jadi nilai setelah kolom npwp dan nama salah ambil kolom mas?

**Comment by wakataw** [comment]
> jadi nilai setelah kolom npwp dan nama salah ambil kolom mas?

oh bukan mas, jadi file *.idx itu menyimpan kategori dan tahun anggaran. Tujuannya untuk filter download detil kalo cuma perlu tahun anggaran tertentu saja untuk spse versi sebelum 4.4

**Comment by oraclecentrino** [comment]
pantesan untuk versi sebelum 4.4 terdownload semua tahun

Mantap Mas
