### ISSUE TITLE
Kolom Geser di export csv

### ISSUE THREAD

**Issue by oraclecentrino** [wakataw/pyproc#43]
Mohon bantuan nya mas untuk export csv itu kolom npwp terisi nilai dari ['jadwal'] jika kolom npwp tersebut kosong dan kolom hasil_negosiasi nilainya banyak yang kosong

seperti digambar ini

![geser](https://user-images.githubusercontent.com/15371904/133755613-c064598a-5e6d-4fff-bbd8-e4d0f3e386c7.JPG)

terima kasih

**Comment by wakataw** [comment]
oh iya ini mas, saya baru lihat juga

**Comment by wakataw** [comment]
bisa dicoba lagi mas

**Comment by oraclecentrino** [comment]
Siap mas

tapi ketika export ke csv ada pesan error mas, untuk case tertentu aja seh

pesan errornya seperti di gmbar ini

![error_lpse_new111](https://user-images.githubusercontent.com/15371904/133911969-e28f5a68-45a7-4c21-a2d0-950eba24f6bf.JPG)

Terima Kasih
