### ISSUE TITLE
isi kolom kosong filter manual tahun anggaran

### ISSUE THREAD

**Issue by oraclecentrino** [wakataw/pyproc#44]
ijin mas untuk export ke csv LPSE Versi <4.4 itu yg tahun anggaran nya di filter manual untuk kolom 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\HP\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\HP\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

npwp | nama_peserta | penawaran | penawaran_terkoreksi | hasil_negosiasi | alamat | p | pk
-- | -- | -- | -- | -- | -- | -- | --

</body>

</html>

ini tidak ada isinya

trims

saya nyoba download di : 
http://lpse.malinau.go.id/eproc4
https://lpse.penajamkab.go.id/eproc4

**Comment by wakataw** [comment]
bisa dicoba lagi mas?
ini saya coba aman, datanya ada
