### ISSUE TITLE
Export CSV Geser satu Line

### ISSUE THREAD

**Issue by oraclecentrino** [wakataw/pyproc#45]
Mohon bantuan nya mas, untuk yg export csv itu jika ada beberapa data yang jika di export ke csv itu datanya turun satu line sehingga tidak terdetek untuk data setelahnya

contohnya untuk LPSE Kota Pekalongan ini :

kode tender : 3566091 ini kolom nama_tendernya geser sehingga untuk data tanggal_pembuatan dst tidak terdeteksi satu row

![pyproc_errorrrr](https://user-images.githubusercontent.com/15371904/135823995-e008ec15-a938-4dde-8835-dfa5cbb2e01b.JPG)

Terima Kasih

**Comment by wakataw** [comment]
![image](https://user-images.githubusercontent.com/20858631/135947794-dba6d40f-c0a9-46f2-94b1-bd5e9355c083.png)

Ini salah dipengolahan data aja kayanya mas. Pastikan quote charnya diset. Ini ngolahnya pake apa?

**Comment by wakataw** [comment]
![image](https://user-images.githubusercontent.com/20858631/135948063-e9b372bc-1a27-46c4-87dd-5edb5acff6a9.png)

Kalo pake excel power query, bisa di set dulu bagian Line breaksnya
