### ISSUE TITLE
Use pydantic as data schema

### ISSUE THREAD

**Issue by wakataw** [wakataw/pyproc#55]
# Generate Data Schema

- [x] Index (369f011571935ba6db8d001d47797a48f8385979, 005e7775fa0c1bba500778ae4c28f5db499a5168)
- [x] Pengumuman (9b9471b007b3454334dc061769018acc47a47f1f)
- [x] Peserta (16e3df3c8af0d74398a6509d99b9eff2167bd422)
- [x] Hasil Evaluasi (a2fc1613d5b2781ed3b31d714997a487ae86bc0e)
- [x] #60 
- [x] #61 

# Schema Implementation
- [ ] #62 
- [ ] #63 
- [ ] #64

**Comment by ayahaceh** [comment]
Apa bisa dijadikan sebuah website ini ya? sy krg paham Python
