### ISSUE TITLE
Using mysql instead of sqllite

### ISSUE THREAD

**Issue by csahat** [wakataw/pyproc#75]
How can I use mysql or mariadb database to save the parsing result instead of sqllite3?

**Comment by wakataw** [comment]
It is not possible right now. All the connection string and SQL are hardcoded inside [scripts/downloader.py](https://github.com/wakataw/pyproc/blob/master/scripts/downloader.py).

But, you can create your own downloader implementation using `Lpse` object as mentioned in documentation [here](https://github.com/wakataw/pyproc#penggunaan-pyproc-sebagai-package).
